import {
  VRA,
  MAT,
  ELE,
  TEO,
  ELP,
  FIS,
  QIM,
  BIO,
  EDU,
  PSI,
  LET,
  INT,
  DEF,
  FON,
  MEF,
} from "./colors";

export const ramos2023 = [
  {
    id: 1,
    code: "MAT1000",
    course: "Precálculo",
    semester: "I",
    year: 1,
    cc: MAT,
    cr: 10,
    req: [],
  },
  {
    id: 2,
    code: "BIO141C",
    course: "Biología de la Célula",
    semester: "I",
    year: 1,
    cc: BIO,
    cr: 10,
    req: [],
  },
  {
    id: 3,
    code: "MEF102A",
    course: "Anatomía General y del Desarrollo",
    semester: "I",
    year: 1,
    cc: MEF,
    cr: 10,
    req: [],
  },
  {
    id: 4,
    code: "FON101A",
    course: "Introducción a la Fonoaudilogía",
    semester: "I",
    year: 1,
    cc: FON,
    cr: 5,
    req: [],
  },
  {
    id: 5,
    code: "PSI1101",
    course: "Procesos Psicológicos Básicos",
    semester: "I",
    year: 1,
    cc: PSI,
    cr: 10,
    req: [],
  },
  {
    id: 6,
    code: "LET011F",
    course: "Fundamentos Linguisticos para Fonoaudiología",
    semester: "I",
    year: 1,
    cc: LET,
    cr: 5,
    req: [],
  },

  {
    id: 7,
    code: "VRA100C",
    course: "Español",
    semester: "I",
    year: 1,
    cc: VRA,
    req: [],
  },

  {
    id: 8,
    code: "VRA2000",
    course: "English Test",
    semester: "I",
    year: 1,
    cc: VRA,
    req: [],
  },
  {
    id: 9,
    code: "FIS122F",
    course: "Física Acústica",
    semester: "II",
    year: 1,
    cc: FIS,
    cr: 10,
    req: [{ id: 1, cc: MAT }],
  },
  {
    id: 10,
    code: "BIO135F",
    course: "Fisiología",
    semester: "II",
    year: 1,
    cc: BIO,
    cr: 10,
    req: [{ id: 2, cc: BIO }],
  },
  {
    id: 11,
    code: "MEF105A",
    course: "Anatomía de Cabeza, Cuello y Neuroanatomía",
    semester: "II",
    year: 1,
    cc: MEF,
    cr: 10,
    req: [{ id: 3, cc: MEF }],
  },
  {
    id: 12,
    code: "LET012F",
    course: "Morfosintaxis del Español",
    semester: "II",
    year: 1,
    cc: MEF,
    cr: 10,
    req: [{ id: 6, cc: LET }],
  },
  {
    id: 13,
    course: "Formación General",
    semester: "II",
    year: 1,
    cc: ELE,
    cr: 10,
    req: [],
  },
  {
    id: 14,
    code: "MEF205A",
    course: "Bioestadística",
    semester: "III",
    year: 2,
    cc: MEF,
    cr: 5,
    req: [{ id: 1, cc: MAT }],
  },
  {
    id: 15,
    code: "MEF201B",
    course: "Fisiopatología",
    semester: "III",
    year: 2,
    cc: MEF,
    cr: 10,
    req: [{ id: 10, cc: BIO }],
  },
  {
    id: 16,
    code: "LET015F",
    course: "Semántica y Pragmática",
    semester: "III",
    year: 2,
    cc: LET,
    cr: 10,
    req: [{ id: 12, cc: LET }],
  },
  {
    id: 17,
    code: "LET013F",
    course: "Fonética, Fonología",
    semester: "III",
    year: 2,
    cc: LET,
    cr: 10,
    req: [{ id: 6, cc: LET }],
  },
  {
    id: 18,
    code: "FON206A",
    course: "Curso de Vida y Desarrollo Humano",
    semester: "III",
    year: 2,
    cc: FON,
    cr: 5,
    req: [
      { id: 4, cc: FON },
      { id: 10, cc: BIO },
    ],
  },
  {
    id: 19,
    course: "Formación Teológica",
    semester: "III",
    year: 2,
    cc: TEO,
    cr: 10,
    req: [],
  },
  {
    id: 20,
    code: "FON208A",
    course: "Salud Pública y Comunitaria",
    semester: "IV",
    year: 2,
    cc: FON,
    cr: 5,
    req: [{ id: 14, cc: MEF }],
  },
  {
    id: 21,
    code: "FON204A",
    course: "Evaluación Audiológica Convencional",
    semester: "IV",
    year: 2,
    cc: FON,
    cr: 10,
    req: [
      { id: 9, cc: FIS },
      { id: 11, cc: MEF },
    ],
  },
  {
    id: 22,
    code: "FON207A",
    course: "Sistema Nervioso en el Curso de Vida",
    semester: "IV",
    year: 2,
    cc: FON,
    cr: 10,
    req: [{ id: 11, cc: MEF, id: 15, cc: MEF }],
  },
  {
    id: 23,
    code: "FON203A",
    course: "Psicolingüistica Evolutiva",
    semester: "IV",
    year: 2,
    cc: FON,
    cr: 5,
    req: [
      { id: 12, cc: LET },
      { id: 16, cc: LET },
      { id: 17, cc: LET },
      { id: 18, cc: FON },
    ],
  },
  {
    id: 24,
    code: "FIL2001",
    course: "Filosofía ¿Para Qué?",
    semester: "IV",
    year: 2,
    cc: FIS,
    cr: 10,
    req: [],
  },
  {
    id: 25,
    course: "Formación General",
    semester: "IV",
    year: 2,
    cc: ELE,
    cr: 10,
    req: [],
  },
  {
    id: 26,
    code: "FON314A",
    course: "Promoción en Salud",
    semester: "V",
    year: 3,
    cc: FON,
    cr: 5,
    req: [
      { id: 14, cc: MEF },
      { id: 18, cc: FON },
    ],
  },
  {
    id: 27,
    code: "FON301A",
    course: "Evaluación Audiológica Objetiva y Otoneurología",
    semester: "V",
    year: 3,
    cc: FON,
    cr: 10,
    req: [{ id: 21, cc: FON }],
  },
  {
    id: 28,
    code: "FON303A",
    course: "Eufonía",
    semester: "V",
    year: 3,
    cc: FON,
    cr: 5,
    req: [{ id: 18, cc: FON }],
  },
  {
    id: 29,
    code: "FON312A",
    course: "Fonoaudiología en Educación",
    semester: "V",
    year: 3,
    cc: FON,
    cr: 10,
    req: [{ id: 23, cc: FON }],
  },
  {
    id: 30,
    code: "FON315A",
    course: "Motricidad Orofacial",
    semester: "V",
    year: 3,
    cc: FON,
    cr: 10,
    req: [{ id: 11, cc: MEF }],
  },
  {
    id: 31,
    code: "",
    course: "Formación General",
    semester: "V",
    year: 3,
    cc: ELE,
    cr: 10,
    req: [],
  },
  {
    id: 32,
    code: "FON304A",
    course: "Evaluación de la Comunicación en Niñas, Niños y Adolescentes",
    semester: "VI",
    year: 3,
    cc: FON,
    cr: 5,
    req: [
      { id: 29, cc: FON },
      { id: 30, cc: FON },
    ],
  },
  {
    id: 33,
    code: "FON305A",
    course: "Evaluación Audiológica Objetiva y Otoneurología",
    semester: "VI",
    year: 3,
    cc: FON,
    cr: 10,
    req: [{ id: 27, cc: FON }],
  },
  {
    id: 34,
    code: "FON313A",
    course: "Evaluación y Diagnóstico Vocal",
    semester: "VI",
    year: 3,
    cc: FON,
    cr: 5,
    req: [
      { id: 14, cc: MEF },
      { id: 28, cc: FON },
    ],
  },
  {
    id: 35,
    code: "FON311A",
    course: "Bioética",
    semester: "VI",
    year: 3,
    cc: FON,
    cr: 10,
    req: [],
  },
  {
    id: 36,
    code: "FON310A",
    course: "Neuropsicología del Lenguaje",
    semester: "VI",
    year: 3,
    cc: FON,
    cr: 10,
    req: [
      { id: 5, cc: PSI },
      { id: 11, cc: MEF },
      { id: 18, cc: FON },
      { id: 22, cc: FON },
    ],
  },
  {
    id: 37,
    code: "",
    course: "Formación General",
    semester: "VI",
    year: 3,
    cc: ELE,
    cr: 10,
    req: [],
  },
  {
    id: 38,
    code: "FON406A",
    course: "Intervención de la Comunicación en Niñas, Niños y Adolescentes",
    semester: "VII",
    year: 4,
    cc: FON,
    cr: 10,
    req: [
      { id: 32, cc: FON },
      { id: 36, cc: FON },
    ],
  },
  {
    id: 39,
    code: "FON403A",
    course: "Evaluación de la Comunicación en Adultos",
    semester: "VII",
    year: 4,
    cc: FON,
    cr: 10,
    req: [
      { id: 18, cc: FON },
      { id: 22, cc: FON },
      { id: 36, cc: FON },
    ],
  },
  {
    id: 40,
    code: "FON404A",
    course: "Intervención Vocal",
    semester: "VII",
    year: 4,
    cc: FON,
    cr: 10,
    req: [{ id: 34, cc: FON }],
  },

  {
    id: 41,
    code: "FON413A",
    course: "Fundamentos de Investigación y Formulación de Proyectos",
    semester: "VII",
    year: 4,
    cc: FON,
    cr: 5,
    req: [
      { id: 14, cc: MEF },
      { id: 35, cc: FON },
    ],
  },
  {
    id: 42,
    code: "FON414X",
    course: "Optativo",
    semester: "VII",
    year: 4,
    cc: FON,
    cr: 5,
    req: [],
  },

  {
    id: 43,
    code: "",
    course: "Formación General",
    semester: "VII",
    year: 4,
    cc: ELE,
    cr: 10,
    req: [],
  },

  {
    id: 44,
    code: "MEF401A",
    course: "Gestión en Organizaciones de Salud",
    semester: "VIII",
    year: 4,
    cc: MEF,
    cr: 5,
    req: [{ id: 26, cc: FON }],
  },
  {
    id: 45,
    code: "FON407A",
    course: "Intervención Fonoaudiológica en Adultos",
    semester: "VIII",
    year: 4,
    cc: FON,
    cr: 10,
    req: [{ id: 39, cc: FON }],
  },
  {
    id: 46,
    code: "FON402A",
    course: "Alteraciones de la Deglución y Alimentación en el Curso de Vida",
    semester: "VIII",
    year: 4,
    cc: FON,
    cr: 10,
    req: [
      { id: 22, cc: FON },
      { id: 30, cc: FON },
    ],
  },
  {
    id: 47,
    code: "FON405A",
    course: "Investigación Fonoaudiológica Aplicada",
    semester: "VIII",
    year: 4,
    cc: FON,
    cr: 10,
    req: [
      { id: 21, cc: FON },
      { id: 32, cc: FON },
      { id: 34, cc: FON },
      { id: 39, cc: FON },
      { id: 41, cc: FON },
    ],
  },
  {
    id: 48,
    code: "FON415X",
    course: "Optativo",
    semester: "VIII",
    year: 4,
    cc: FON,
    cr: 5,
    req: [],
  },
  {
    id: 49,
    code: "",
    course: "Formación General",
    semester: "VIII",
    year: 4,
    cc: ELE,
    cr: 10,
    req: [],
  },
  {
    id: 50,
    code: "FON501A",
    course: "Internado Clínico",
    semester: "IX",
    year: 5,
    cc: FON,
    cr: 20,
    req: [
      { id: 38, cc: FON },
      { id: 40, cc: FON },
      { id: 44, cc: MEF },
      { id: 45, cc: FON },
      { id: 46, cc: FON },
      { id: 47, cc: FON },
    ],
  },
  {
    id: 51,
    code: "FON502A",
    course: "Internado Clínico Adulto",
    semester: "IX",
    year: 5,
    cc: FON,
    cr: 20,
    req: [
      { id: 38, cc: FON },
      { id: 40, cc: FON },
      { id: 44, cc: MEF },
      { id: 45, cc: FON },
      { id: 46, cc: FON },
      { id: 47, cc: FON },
    ],
  },
  {
    id: 52,
    code: "FON503A",
    course: "Internado Clínico Infanto-Juvenil",
    semester: "IX",
    year: 5,
    cc: FON,
    cr: 20,
    req: [
      { id: 38, cc: FON },
      { id: 40, cc: FON },
      { id: 44, cc: MEF },
      { id: 45, cc: FON },
      { id: 46, cc: FON },
      { id: 47, cc: FON },
    ],
  },

  {
    id: 53,
    code: "FON506A",
    course: "Internado en Audiología",
    semester: "X",
    year: 5,
    cc: FON,
    cr: 20,
    req: [
      { id: 38, cc: FON },
      { id: 40, cc: FON },
      { id: 44, cc: MEF },
      { id: 45, cc: FON },
      { id: 46, cc: FON },
      { id: 47, cc: FON },
    ],
  },
  {
    id: 54,
    code: "FON504A",
    course: "Internado en Voz",
    semester: "X",
    year: 5,
    cc: FON,
    cr: 20,
    req: [
      { id: 38, cc: FON },
      { id: 40, cc: FON },
      { id: 44, cc: MEF },
      { id: 45, cc: FON },
      { id: 46, cc: FON },
      { id: 47, cc: FON },
    ],
  },
  {
    id: 55,
    code: "FON507A",
    course: "Internado Electivo",
    semester: "X",
    year: 5,
    cc: FON,
    cr: 15,
    req: [
      { id: 38, cc: FON },
      { id: 40, cc: FON },
      { id: 44, cc: MEF },
      { id: 45, cc: FON },
      { id: 46, cc: FON },
      { id: 47, cc: FON },
    ],
  },
];
