import { VRA, MAT, ELE, TEO, ELP, FIS, QIM, BIO, EDU, PSI, LET, INT,DEF,FON,MEF } from "./colors";

export const ramos2023 = [
    {
        id: 1,
        code: "MAT1023",
        course: "Cálculo",
        semester: 'I',
        year: 1,
        cc: MAT,
        cr: 10,
        req: [],
      },
      {
        id: 2,
        code: "QIM201F",
        course: "Química",
        semester: 'I',
        year: 1,
        cc: QIM,
        cr: 10,
        req: [],
      },
      {
        id: 3,
        code: "BIO141C",
        course: "Biología de la Célula",
        semester: 'I',
        year: 1,
        cc: BIO,
        cr: 10,
        req: [],
      },
      {
        id: 4,
        code: "MEF101A",
        course: "Introducción a la Anatomía",
        semester: 'I',
        year: 1,
        cc: MEF,
        cr: 5,
        req: [],
      },
      {
        id: 5,
        code: "FON101",
        course: "Introducción a la Fonoaudilogía",
        semester: 'I',
        year: 1,
        cc: FON,
        cr: 5,
        req: [],
      },
    
      {
        id: 6,
        code: "PSI1101",
        course: "Procesos Psicológicos Básicos",
        semester: 'I',
        year: 1,
        cc: PSI,
        cr: 10,
        req: [],
      },
    
      {
        id: 7,
        code: "VRA100C",
        course: "Examen de Comunicación Escrita",
        semester: 'I',
        year: 1,
        cc: VRA,
        req: [],
      },
    
      {
        id: 8,
        code: "VRA2000",
        course: "English Test",
        semester: 'I',
        year: 1,
        cc: VRA,
        req: [],
      },
      {
        id: 9,
        code: "FIS121F",
        course: "Física para Fonoaudiología",
        semester: 'II',
        year: 1,
        cc: FIS,
        cr: 10,
        req: [],
      },
      {
        id: 10,
        code: "BIO135F",
        course: "Fisiología",
        semester: 'II',
        year: 1,
        cc: BIO,
        cr: 10,
        req: [
          { id: 3, cc: BIO },
          { id: 4, cc: MEF },
        ],
      },
      {
        id: 11,
        code: "MEF103A",
        course: "Bioestadística",
        semester: 'II',
        year: 1,
        cc: MEF,
        cr: 10,
        req: [{ id: 1, cc: MAT }],
      },
]